backend:
  name: git-gateway
  branch: master # Branch to update

media_folder: "src/img"
public_folder: "/img"

collections:

  - name: "main"
    label: "основные данные"
    files:
      - label: "О фирме"
        name: "metadata"
        file: "src/_data/metadata.json"
        fields:
          - {label: Титул, name: title, widget: string}
          - {label: URL, name: url, widget: string}
          - {label: Заголовок, name: description, widget: string}
          - {label: Описание, name: longdescription, widget: string}
      - label: "Заголовки"
        name: "titles"
        file: "src/_data/titles.json"
        fields:
          - {label: "Адреса", name: "addresses", widget: "string"}
          - {label: "контакты", name: "contactos", widget: "string"}
          - {label: "Преимущества", name: "benefits", widget: "string"}
          - {label: "Товары", name: "products", widget: "string"}
          - {label: "Нижнее меню", name: "footermenu", widget: "string"}
          - {label: "над заголовоком", name: "subtitle", widget: "string"}
      - label: "Преимущества"
        name: "benefits"
        file: "src/_data/features.json"
        fields:
          - label: "Преимущества"
            name: "items"
            widget: "list"
            fields:
            - {label: "Заголовок", name: "title", widget: "string"}
            - {label: "Подзаголовок", name: "subtitle", widget: "string"}
            - {label: "текст", name: "text", widget: "string"}
      - label: "Контакты"
        name: "contacts"
        file: "src/_data/contacts.json"
        fields:
          - {label: "phone", name: "phone", widget: "string"}
          - {label: "whatsapp", name: "whatsapp", widget: "string"}
          - {label: "email", name: "email", widget: "string"}
          - label: "Филиал 1"
            name: "filial_1"
            widget: "object"
            fields:
              - {label: "Город", name: "city", widget: "string"}
              - {label: "Адрес", name: "address", widget: "string"}
          - label: "Филиал 2"
            name: "filial_2"
            widget: "object"
            fields:
              - {label: "Город", name: "city", widget: "string"}
              - {label: "Адрес", name: "address", widget: "string"}
  - name: "palets"
    label: "Палеты"
    folder: "src/palets"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "tipo", name: "tipo", widget: "string"}
      - {label: "uso", name: "uso", widget: "string"}
      - {label: "Tipo de especies", name: "woodtype", widget: "string"}
      - {label: "Especie", name: "wood", widget: "string"}
      - {label: "condicion", name: "condicion", widget: "string"}
      - {label: "region", name: "region", widget: "string"}
      - {label: "volumen", name: "volumen", widget: "string"}
      - {label: "Altura", name: "height", widget: "string"}
      - {label: "Grosor", name: "thickness", widget: "string"}
      - {label: "Ancho", name: "width", widget: "string"}
      - {label: "Largo", name: "length", widget: "string"}
      - {label: "Marca", name: "mark", widget: "string"}
      - {label: "tablas de capa superior", name: "board", widget: "string"}
      - {label: "tablas transversales", name: "traverse", widget: "string"}
      - {label: "Sistema", name: "system", widget: "string"}
      - {label: "calidad", name: "calidad", widget: "string"}
      - {label: "desecado", name: "desecado", widget: "string"}
      - {label: "price", name: "price", widget: "string"}
      - {label: "fechaDeEntrega", name: "fechaDeEntrega", widget: "string"}
      - {label: "vendePara", name: "vendePara", widget: "string"}
      - {label: "date", name: "date", widget: "string"}
      - {label: "img", name: "img", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list" }
      - {label: "Полное описание", name: "body", widget: "markdown"}

  - name: "madera"
    label: "Древесина"
    folder: "src/madera"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "tipo", name: "tipo", widget: "string"}
      - {label: "uso", name: "uso", widget: "string"}
      - {label: "Tipo de especies", name: "woodtype", widget: "string"}
      - {label: "Especie", name: "wood", widget: "string"}
      - {label: "condicion", name: "condicion", widget: "string"}
      - {label: "region", name: "region", widget: "string"}
      - {label: "volumen", name: "volumen", widget: "string"}
      - {label: "Altura", name: "height", widget: "string"}
      - {label: "Grosor", name: "thickness", widget: "string"}
      - {label: "Ancho", name: "width", widget: "string"}
      - {label: "Largo", name: "length", widget: "string"}
      - {label: "Marca", name: "mark", widget: "string"}
      - {label: "tablas de capa superior", name: "board", widget: "string"}
      - {label: "tablas transversales", name: "traverse", widget: "string"}
      - {label: "Sistema", name: "system", widget: "string"}
      - {label: "calidad", name: "calidad", widget: "string"}
      - {label: "desecado", name: "desecado", widget: "string"}
      - {label: "price", name: "price", widget: "string"}
      - {label: "fechaDeEntrega", name: "fechaDeEntrega", widget: "string"}
      - {label: "vendePara", name: "vendePara", widget: "string"}
      - {label: "date", name: "date", widget: "string"}
      - {label: "img", name: "img", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list" }
      - {label: "Полное описание", name: "body", widget: "markdown"}
